(setq skk-dcomp-activate t)
(setq skk-dcomp-multiple-activate t)

(when (memq 'skk-dcomp-multiple-face (face-list))
  ;; dcomp-multiple supported
  (progn
    (set-face-foreground 'skk-dcomp-multiple-face "black")
    (set-face-background 'skk-dcomp-multiple-face "lightgray")
    (set-face-foreground 'skk-dcomp-multiple-trailing-face "yellow")
    (set-face-background 'skk-dcomp-multiple-selected-face "blue")))

(setq skk-egg-like-newline t)
(setq skk-henkan-strict-okuri-precedence t)
(setq skk-show-annotation t)
(require 'skk-hint)
(require 'skk-study)

;; SandS (works only for the first character)
(loop for k from ?a to ?z do
      (space-chord-define skk-j-mode-map k (upcase (char-to-string k))))

(setq-default skk-kutouten-type 'en)
(setq my-skk-rom-kana-rule-list-base
      (append
       '(
         ("h." nil ".")
         ("h," nil ",")
         ("h!" nil "!")
         ("h?" nil "?")
         ("h;" nil ";")
         ("h:" nil ":")
         ("h-" nil "-")
         ("h~" nil "~")
         ("h/" nil "/")
         ("h@" nil "@")
         ("h=" nil "=")
         ("h(" nil "(")
         ("h)" nil ")")
         ("h[" nil "[")
         ("h]" nil "]")
         ("h<" nil "<")
         ("h>" nil ">")
         ("h\\" nil "\\")
         ("h$" nil "$")
         ("ht" nil "\t")
         ("z " nil "　")
         ("z." nil "。")
         ("z," nil "、")
         ("z!" nil "！")
         ("z?" nil "？")
         ("z;" nil "；")
         ("z:" nil "：")
         ("z-" nil "ー")
         ("z~" nil "〜")
         ("z/" nil "・")
         ("z@" nil "＠")
         ("z=" nil "＝")
         ("z(" nil "（")
         ("z)" nil "）")
         ("z[" nil "「")
         ("z]" nil "」")
         ("z<" nil "＜")
         ("z>" nil "＞")
         ("zz-" nil "…")
         ("zz[" nil "『")
         ("zz]" nil "』")
         ("ca" nil "∧")
         ("co" nil "∨")
         ("cn" nil "¬")
         ("ci" nil "⊃")
         ("cf" nil "⊥")
         ("cy" nil "⇒")
         ("cY" nil "→")
         ("cd" nil "≡")
         ("cA" nil "∀")
         ("cE" nil "∃")
         ("ce" nil "∈")
         ("cu" nil "Π")
         ("cl" nil "λ")
         ("c<" nil "《")
         ("c>" nil "》")
         ("cp" nil "├")
         )
       skk-rom-kana-rule-list))
(setq my-skk-rom-kana-rule-list-en
      (append
       '(
         ("." nil ".")
         ("," nil ",")
         ("!" nil "!")
         ("?" nil "?")
         (";" nil ";")
         (":" nil ":")
       ; ("-" nil "-")
         ("~" nil "~")
       ; ("/" nil "/")
         ("@" nil "@")
         ("=" nil "=")
         ("(" nil "(")
         (")" nil ")")
         ("[" nil "[")
         ("]" nil "]")
         ("<" nil "<")
         (">" nil ">")
       ; ("\\" nil "\\")
       ; ("$" nil "$")
         )
       my-skk-rom-kana-rule-list-base))
(setq my-skk-rom-kana-rule-list-ja
      (append
       '(
         ("." nil "。")
         ("," nil "、")
         ("!" nil "！")
         ("?" nil "？")
         ("-" nil "ー")
         ("@" nil "＠")
         ("[" nil "「")
         ("]" nil "」")
         )
       my-skk-rom-kana-rule-list-base))
(setq my-skk-rom-kana-rule-list-JA
      (append
       '(
         ("." nil "．")
         ("," nil "，")
         ("!" nil "！")
         ("?" nil "？")
         ("-" nil "ー")
         ("@" nil "＠")
         ("[" nil "「")
         ("]" nil "」")
         )
       my-skk-rom-kana-rule-list-base))
(defun skk-reconstruct-rule-tree ()
  (setq skk-rule-tree (skk-compile-rule-list
                       skk-rom-kana-base-rule-list
                       skk-rom-kana-rule-list)))
(defun skk-use-en-signs ()
  (interactive)
  (setq skk-rom-kana-rule-list my-skk-rom-kana-rule-list-en)
  (skk-reconstruct-rule-tree))
(defun skk-use-ja-signs ()
  (interactive)
  (setq skk-rom-kana-rule-list my-skk-rom-kana-rule-list-ja)
  (skk-reconstruct-rule-tree))
(defun skk-use-JA-signs ()
  (interactive)
  (setq skk-rom-kana-rule-list my-skk-rom-kana-rule-list-JA)
  (skk-reconstruct-rule-tree))

(skk-use-en-signs)
(make-variable-buffer-local 'skk-rule-tree)
(make-variable-buffer-local 'skk-rom-kana-rule-list)

(when (featurep 'anything-complete) (alcs-make-candidates))
