#!/bin/zsh

lib=~/.emacs.d/elpa-bootstrap.el
elpa=~/.emacs.d/elpa
packages=~/.emacs.d/packages
themes=~/.emacs.d/themes

function error() {
    echo "$1" >&2
    exit 1
}

function emacs() {
    if [ -n "$EMACS" ]; then
        $EMACS "$@"
    elif whence emacs >/dev/null; then
        command emacs "$@"
    elif whence emacs-snapshot >/dev/null; then
        command emacs-snapshot "$@"
    else
        error 'No emacs command'
    fi
}

[ -f "$elpa/package-list" ] && emacs --batch -l "$lib" -f install-packages
[ -f "$packages/package-list" ] && "$packages/install"
[ -f "$themes/package-list" ] && "$themes/install"
